// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"net/url"

	"github.com/apkatsikas/go-subsonic"
	"github.com/apkatsikas/subcordant/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewICommandHandler creates a new instance of ICommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommandHandler {
	mock := &ICommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ICommandHandler is an autogenerated mock type for the ICommandHandler type
type ICommandHandler struct {
	mock.Mock
}

type ICommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ICommandHandler) EXPECT() *ICommandHandler_Expecter {
	return &ICommandHandler_Expecter{mock: &_m.Mock}
}

// Play provides a mock function for the type ICommandHandler
func (_mock *ICommandHandler) Play(albumId string) error {
	ret := _mock.Called(albumId)

	if len(ret) == 0 {
		panic("no return value specified for Play")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(albumId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ICommandHandler_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type ICommandHandler_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - albumId
func (_e *ICommandHandler_Expecter) Play(albumId interface{}) *ICommandHandler_Play_Call {
	return &ICommandHandler_Play_Call{Call: _e.mock.On("Play", albumId)}
}

func (_c *ICommandHandler_Play_Call) Run(run func(albumId string)) *ICommandHandler_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ICommandHandler_Play_Call) Return(err error) *ICommandHandler_Play_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ICommandHandler_Play_Call) RunAndReturn(run func(albumId string) error) *ICommandHandler_Play_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDiscordClient creates a new instance of IDiscordClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDiscordClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDiscordClient {
	mock := &IDiscordClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IDiscordClient is an autogenerated mock type for the IDiscordClient type
type IDiscordClient struct {
	mock.Mock
}

type IDiscordClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IDiscordClient) EXPECT() *IDiscordClient_Expecter {
	return &IDiscordClient_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type IDiscordClient
func (_mock *IDiscordClient) Init(commandHandler interfaces.ICommandHandler) error {
	ret := _mock.Called(commandHandler)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interfaces.ICommandHandler) error); ok {
		r0 = returnFunc(commandHandler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDiscordClient_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type IDiscordClient_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - commandHandler
func (_e *IDiscordClient_Expecter) Init(commandHandler interface{}) *IDiscordClient_Init_Call {
	return &IDiscordClient_Init_Call{Call: _e.mock.On("Init", commandHandler)}
}

func (_c *IDiscordClient_Init_Call) Run(run func(commandHandler interfaces.ICommandHandler)) *IDiscordClient_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaces.ICommandHandler))
	})
	return _c
}

func (_c *IDiscordClient_Init_Call) Return(err error) *IDiscordClient_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDiscordClient_Init_Call) RunAndReturn(run func(commandHandler interfaces.ICommandHandler) error) *IDiscordClient_Init_Call {
	_c.Call.Return(run)
	return _c
}

// JoinVoiceChat provides a mock function for the type IDiscordClient
func (_mock *IDiscordClient) JoinVoiceChat() (io.Writer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JoinVoiceChat")
	}

	var r0 io.Writer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.Writer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IDiscordClient_JoinVoiceChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinVoiceChat'
type IDiscordClient_JoinVoiceChat_Call struct {
	*mock.Call
}

// JoinVoiceChat is a helper method to define mock.On call
func (_e *IDiscordClient_Expecter) JoinVoiceChat() *IDiscordClient_JoinVoiceChat_Call {
	return &IDiscordClient_JoinVoiceChat_Call{Call: _e.mock.On("JoinVoiceChat")}
}

func (_c *IDiscordClient_JoinVoiceChat_Call) Run(run func()) *IDiscordClient_JoinVoiceChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDiscordClient_JoinVoiceChat_Call) Return(writer io.Writer, err error) *IDiscordClient_JoinVoiceChat_Call {
	_c.Call.Return(writer, err)
	return _c
}

func (_c *IDiscordClient_JoinVoiceChat_Call) RunAndReturn(run func() (io.Writer, error)) *IDiscordClient_JoinVoiceChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewIStreamer creates a new instance of IStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStreamer {
	mock := &IStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IStreamer is an autogenerated mock type for the IStreamer type
type IStreamer struct {
	mock.Mock
}

type IStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *IStreamer) EXPECT() *IStreamer_Expecter {
	return &IStreamer_Expecter{mock: &_m.Mock}
}

// PrepStream provides a mock function for the type IStreamer
func (_mock *IStreamer) PrepStream(inputUrl *url.URL) error {
	ret := _mock.Called(inputUrl)

	if len(ret) == 0 {
		panic("no return value specified for PrepStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*url.URL) error); ok {
		r0 = returnFunc(inputUrl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IStreamer_PrepStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepStream'
type IStreamer_PrepStream_Call struct {
	*mock.Call
}

// PrepStream is a helper method to define mock.On call
//   - inputUrl
func (_e *IStreamer_Expecter) PrepStream(inputUrl interface{}) *IStreamer_PrepStream_Call {
	return &IStreamer_PrepStream_Call{Call: _e.mock.On("PrepStream", inputUrl)}
}

func (_c *IStreamer_PrepStream_Call) Run(run func(inputUrl *url.URL)) *IStreamer_PrepStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*url.URL))
	})
	return _c
}

func (_c *IStreamer_PrepStream_Call) Return(err error) *IStreamer_PrepStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IStreamer_PrepStream_Call) RunAndReturn(run func(inputUrl *url.URL) error) *IStreamer_PrepStream_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function for the type IStreamer
func (_mock *IStreamer) Stream(voice io.Writer) error {
	ret := _mock.Called(voice)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = returnFunc(voice)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IStreamer_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type IStreamer_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - voice
func (_e *IStreamer_Expecter) Stream(voice interface{}) *IStreamer_Stream_Call {
	return &IStreamer_Stream_Call{Call: _e.mock.On("Stream", voice)}
}

func (_c *IStreamer_Stream_Call) Run(run func(voice io.Writer)) *IStreamer_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer))
	})
	return _c
}

func (_c *IStreamer_Stream_Call) Return(err error) *IStreamer_Stream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IStreamer_Stream_Call) RunAndReturn(run func(voice io.Writer) error) *IStreamer_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// NewISubsonicClient creates a new instance of ISubsonicClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISubsonicClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISubsonicClient {
	mock := &ISubsonicClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ISubsonicClient is an autogenerated mock type for the ISubsonicClient type
type ISubsonicClient struct {
	mock.Mock
}

type ISubsonicClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ISubsonicClient) EXPECT() *ISubsonicClient_Expecter {
	return &ISubsonicClient_Expecter{mock: &_m.Mock}
}

// GetAlbum provides a mock function for the type ISubsonicClient
func (_mock *ISubsonicClient) GetAlbum(albumId string) (*subsonic.AlbumID3, error) {
	ret := _mock.Called(albumId)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbum")
	}

	var r0 *subsonic.AlbumID3
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*subsonic.AlbumID3, error)); ok {
		return returnFunc(albumId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *subsonic.AlbumID3); ok {
		r0 = returnFunc(albumId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subsonic.AlbumID3)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(albumId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ISubsonicClient_GetAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbum'
type ISubsonicClient_GetAlbum_Call struct {
	*mock.Call
}

// GetAlbum is a helper method to define mock.On call
//   - albumId
func (_e *ISubsonicClient_Expecter) GetAlbum(albumId interface{}) *ISubsonicClient_GetAlbum_Call {
	return &ISubsonicClient_GetAlbum_Call{Call: _e.mock.On("GetAlbum", albumId)}
}

func (_c *ISubsonicClient_GetAlbum_Call) Run(run func(albumId string)) *ISubsonicClient_GetAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ISubsonicClient_GetAlbum_Call) Return(albumID3 *subsonic.AlbumID3, err error) *ISubsonicClient_GetAlbum_Call {
	_c.Call.Return(albumID3, err)
	return _c
}

func (_c *ISubsonicClient_GetAlbum_Call) RunAndReturn(run func(albumId string) (*subsonic.AlbumID3, error)) *ISubsonicClient_GetAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type ISubsonicClient
func (_mock *ISubsonicClient) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ISubsonicClient_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type ISubsonicClient_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *ISubsonicClient_Expecter) Init() *ISubsonicClient_Init_Call {
	return &ISubsonicClient_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *ISubsonicClient_Init_Call) Run(run func()) *ISubsonicClient_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISubsonicClient_Init_Call) Return(err error) *ISubsonicClient_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ISubsonicClient_Init_Call) RunAndReturn(run func() error) *ISubsonicClient_Init_Call {
	_c.Call.Return(run)
	return _c
}

// StreamUrl provides a mock function for the type ISubsonicClient
func (_mock *ISubsonicClient) StreamUrl(trackId string) (*url.URL, error) {
	ret := _mock.Called(trackId)

	if len(ret) == 0 {
		panic("no return value specified for StreamUrl")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*url.URL, error)); ok {
		return returnFunc(trackId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *url.URL); ok {
		r0 = returnFunc(trackId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(trackId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ISubsonicClient_StreamUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamUrl'
type ISubsonicClient_StreamUrl_Call struct {
	*mock.Call
}

// StreamUrl is a helper method to define mock.On call
//   - trackId
func (_e *ISubsonicClient_Expecter) StreamUrl(trackId interface{}) *ISubsonicClient_StreamUrl_Call {
	return &ISubsonicClient_StreamUrl_Call{Call: _e.mock.On("StreamUrl", trackId)}
}

func (_c *ISubsonicClient_StreamUrl_Call) Run(run func(trackId string)) *ISubsonicClient_StreamUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ISubsonicClient_StreamUrl_Call) Return(uRL *url.URL, err error) *ISubsonicClient_StreamUrl_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *ISubsonicClient_StreamUrl_Call) RunAndReturn(run func(trackId string) (*url.URL, error)) *ISubsonicClient_StreamUrl_Call {
	_c.Call.Return(run)
	return _c
}
